// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucjsiytkmkjamlfrfvir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjanNpeXRrbWtqYW1sZnJmdmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDk1NjYsImV4cCI6MjA2MzgyNTU2Nn0.LqvG4-Ae5tgeOuvxBKFye3BkrE-TSlQSdMFr54dxYCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);